### ISSUE TITLE
[REPORT IN PROGRESS] "Show desktop" icon makes your app disappear when I click on it...

### ISSUE THREAD

**Issue by G1ll0u** [Ross-Patterson/Portals-Desktop-Organization#30]
When clicking on the "back to desktop" icon in the bottom right corner, if I click on one of my portals, it disappears and reappears after my second click so I can't interact with it. 

**HERE'S A GIF:**
![yaX5knOloO](https://user-images.githubusercontent.com/36129824/175120800-b87e28cc-4e8e-4437-bd6a-db39f400306a.gif)

- The problem only appears on the left portal and 
- The problem disappears after reopening any window

My report isnt finished I need to try to reset the soft to defaults and rebuild my portals to see if the problem comes back but I'm too lazy for the moment...

**Comment by Ross-Patterson** [comment]
Hopefully this should be fixed in v2.1.0.5. Let me know if it persists.

**Comment by G1ll0u** [comment]
I can confirm that the problem is gone, but now when I click the "back to desktop" it simply makes Portals disappearing.

I don't know where to factory reset settings so I can't say if it's my specific app settings or your code


Two new ideas 😄 :

Reset to factory defaults button
AND/OR
Reset to factory defaults but keep folders and portal locations

**Comment by heycansun** [comment]
Hello @Ross-Patterson , I'd like to inform you that this bug/problem still occurs for me as a very recent user of Portals. How can I help you to fix it?

**Comment by Ross-Patterson** [comment]
See here for info:
https://github.com/Ross-Patterson/Portals-Desktop-Organization/issues/101#issuecomment-1523977037

Unfortunately this is a Microsoft limitation and I can only work around it. Microsoft does not let developers override the "Show Desktop" command (for good reason).
